# Generated by Django 4.2.23 on 2025-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='modelName',
            field=models.TextField(default='deepseek-chat'),
        ),
    ]
