# Generated by Django 4.2.23 on 2025-08-31 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_usersetting_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='daily_message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='last_message_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='user_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
