# Generated by Django 4.2.23 on 2025-08-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_usersetting_daily_message_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='tts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='tts_language',
            field=models.CharField(choices=[('中文', '中文'), ('日语', '日语')], default='中文', max_length=10),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='tts_length_scale',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='tts_noise_scale',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='tts_noise_scale_w',
            field=models.FloatField(default=0.668),
        ),
    ]
