# Generated by Django 4.2.23 on 2025-08-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_usersetting_tts_enabled_usersetting_tts_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='tts_api_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tts_language',
            field=models.CharField(choices=[('中文', '中文'), ('日语', '日语')], default='日语', max_length=10),
        ),
    ]
